


ODS HTML PATH="&JES.SG/S_8_3" (URL=NONE) BODY="Bar.html";
ODS GRAPHICS ON / RESET IMAGENAME="F8_5_";

TITLE "VBAR";
PROC SGPLOT DATA=JES.Results;
	VBAR Vendor /RESPONSE=Resistance STAT=MEAN;
RUN; 

TITLE "HBAR";
PROC SGPLOT DATA=JES.Results;
	HBAR Vendor /RESPONSE=Resistance STAT=MEAN;
RUN; 

TITLE "VBAR with Confidence Limits";
PROC SGPLOT DATA=JES.Results;
	VBAR Vendor / RESPONSE=Resistance STAT=MEAN
	LIMITS=BOTH LIMITSTAT=CLM ALPHA=0.10;
RUN;

TITLE "HBAR with Confidence Limits";
PROC SGPLOT DATA=JES.Results;
	HBAR Vendor / RESPONSE=Resistance STAT=MEAN
	LIMITS=BOTH LIMITSTAT=CLM ALPHA=0.10;
RUN;

TITLE "VBAR and VLINE";
PROC SGPLOT DATA=JES.Results;
	VBAR  Vendor /RESPONSE=Defects STAT=MEAN;
	VLINE Vendor /RESPONSE=Fail STAT=MEAN;
RUN;

TITLE "HBAR and HLINE";
PROC SGPLOT DATA=JES.Results;
	HBAR  Vendor /RESPONSE=Defects STAT=MEAN;
	HLINE Vendor /RESPONSE=Fail STAT=MEAN;
RUN;

ODS GRAPHICS OFF;
ODS HTML CLOSE;



