


ODS HTML PATH="&JES.SG/S_8_3" (URL=NONE) BODY="By_Group.html";
ODS GRAPHICS ON / RESET IMAGENAME="F8_7_";

TITLE "Mean Resistance by Month";
PROC SGPLOT DATA=JES.Results_Tab; BY Vendor;
	SERIES Y=M_Res X=Mon;
RUN; 

ODS GRAPHICS / RESET IMAGENAME="F8_8_";
PROC SGPLOT DATA=JES.Results_Tab;
	SERIES Y=M_Res X=Mon /  GROUP=Vendor;
RUN;

ODS GRAPHICS OFF;
ODS HTML CLOSE;
