



ODS HTML PATH="&JES.SG/S_8_3" (URL=NONE) BODY="Distribution.html";
ODS GRAPHICS ON / RESET IMAGENAME="F8_4_";

TITLE "VBOX";
PROC SGPLOT DATA=JES.Results;
	VBOX Resistance / CATEGORY=Vendor;
RUN; 

TITLE "HBOX";
PROC SGPLOT DATA=JES.Results;
	HBOX Resistance / CATEGORY=Vendor;
RUN; 

TITLE "HISTOGRAM";
PROC SGPLOT DATA=JES.Results;
	HISTOGRAM Resistance;
RUN;

TITLE "DENSITY";
PROC SGPLOT DATA=JES.Results;
	DENSITY Resistance;
RUN;

TITLE "HISTOGRAM and DENSITY";
PROC SGPLOT DATA=JES.Results;
	HISTOGRAM Resistance;
	DENSITY Resistance;
RUN; 

ODS GRAPHICS OFF;
ODS HTML CLOSE;

