



ODS HTML PATH="&JES.SG/S_8_3" (URL=NONE) BODY="histo_density.html";
ODS GRAPHICS ON / RESET IMAGENAME="F8_20_";

TITLE "Distribution of Resistance";
PROC SGPLOT DATA=JES.Results;
	HISTOGRAM Resistance /
		BOUNDARY=UPPER
		SCALE=COUNT
		FILL FILLATTRS=(COLOR=GRAYE0)
		OUTLINE;
	DENSITY Resistance / 
		TYPE=NORMAL(MU=15 SIGMA=3) LEGENDLABEL="Normal(15, 3)" 
		LINEATTRS=(COLOR=Red PATTERN=Dot);
	DENSITY Resistance / 
		TYPE=KERNEL LEGENDLABEL="Kernel Fit" 
		LINEATTRS=(COLOR=Green PATTERN=Dash) ;
		REFLINE 12.5 22.5 / AXIS=X LABEL=("LSL=12.5" "USL=22.5")
		LINEATTRS=(COLOR=GRAY PATTERN=Dash)
		LABELLOC=OUTSIDE LABELPOS=MAX;
RUN; 

ODS GRAPHICS OFF;
ODS HTML CLOSE;

