

GOPTIONS RESET=ALL GUNIT=PCT HTEXT=3 FTEXT='Arial' BORDER; 

/*===== Uncomment the next two lines to send graphic output to a postscript file  
FILENAME Fig "c:\JES\figures\Chapter_5\";
GOPTIONS DEVICE=PSLEPSFC XMAX=6IN YMAX=4IN GSFNAME=Fig GSFMODE=REPLACE;   =====*/

TITLE1 HEIGHT=5 "Skeletal Box Plot";
PROC BOXPLOT DATA=JES.Results_Q4;
	PLOT Resistance*Vendor /BOXSTYLE=SKELETAL;
RUN; QUIT;

PROC BOXPLOT DATA=JES.Results_Q4;
	PLOT Resistance*Vendor /BOXSTYLE=SKELETAL 
	BOXCONNECT=MEAN
	BOXWIDTH=7
	NOTCHES;
RUN; QUIT;

TITLE1 HEIGHT=5 "Schematic Box Plot";
PROC BOXPLOT DATA=JES.Results_Q4;
	PLOT Resistance*Vendor /BOXSTYLE=SCHEMATIC; 
RUN; QUIT;


PROC BOXPLOT DATA=JES.Results_Q4;
	PLOT Resistance*Vendor / BOXSTYLE=SCHEMATICID
	CBOXFILL=GRAYD0
	CBOXES=GREEN
	IDSYMBOL=dot
	IDCOLOR=RED
	BOXWIDTH=10 
	BOXWIDTHSCALE=.5
	BWSLEGEND; 
	ID Resistance;
RUN; QUIT;


