

GOPTIONS RESET=ALL;

ODS HTML PATH="&JES.SG/S_10_6" (URL=NONE) BODY="MCF.html";

ODS GRAPHICS ON / RESET IMAGENAME="F10_11_";
ODS OUTPUT MCFEST=MCF_by_Vendor;
TITLE1 HEIGHT=5 "Cumulative Repairs vs Unit Age by Vendor";
PROC RELIABILITY DATA=JES.Repair;
		UNITID SN;
		MCFPLOT EventTime*Censor(-1)=Vendor /
		INTERPOLATE=STEP NOCENPRINT 
		OVERLAY ;
RUN;

ODS GRAPHICS OFF;
ODS HTML CLOSE;

