


ODS LISTING  GPATH="&JES.SG/S_8_2"  IMAGE_DPI=300;
ODS GRAPHICS ON / RESET IMAGENAME="F8_1_" IMAGEFMT=PNG;

PROC LIFETEST DATA=JES.LifeTest;
	TIME TestTime*Censor(-1);
	STRATA Temp_C;
RUN;

ODS GRAPHICS OFF;


GOPTIONS RESET=ALL;
ODS _ALL_ CLOSE;
ODS LATEX PATH="&JES.SG/S_8_2" BODY="Lifetest.tex" IMAGE_DPI=300;
ODS RTF PATH  ="&JES.SG/S_8_2" BODY="Lifetest.rtf" IMAGE_DPI=300;
ODS HTML  PATH="&JES.SG/S_8_2" (URL=NONE) BODY="Lifetest.html";
ODS GRAPHICS ON / RESET IMAGENAME="F8_1_";

PROC LIFETEST DATA=JES.LifeTest;
	TIME TestTime*Censor(-1);
	STRATA Temp_C;
RUN;

ODS GRAPHICS OFF;
ODS _ALL_ CLOSE;
ODS LISTING;






