


%LET USER=my_user; %LET pw =my_password; %LET PW=my_path;
 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PW="&path");
    CREATE TABLE DB_Tables as
    SELECT * FROM CONNECTION TO ORACLE
      (SELECT OWNER, TABLE_NAME, NUM_ROWS, AVG_ROW_LEN  FROM ALL_TABLES);
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;


 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PW="&path");
    CREATE TABLE DB_Views as
    SELECT * FROM CONNECTION TO ORACLE
      (SELECT OWNER, VIEW_NAME FROM ALL_VIEWS);
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;


 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PW="&path");
    CREATE TABLE Units_Fields as
    SELECT * FROM CONNECTION TO ORACLE
    (SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_Length
             FROM ALL_TAB_COLUMNS   WHERE TABLE_NAME='Units' );
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;

 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PW="&path");
    CREATE TABLE Units_Rows as
    SELECT * FROM CONNECTION TO ORACLE
    (SELECT * FROM Units  WHERE ROWNUM <= 50  );
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;

 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PW="&path");
    CREATE TABLE Fails_Fields as
    SELECT * FROM CONNECTION TO ORACLE
    (SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH
             FROM ALL_TAB_COLUMNS   WHERE TABLE_NAME='Fails' );
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;

 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PW="&path");
    CREATE TABLE Fails_Rows as
    SELECT * FROM CONNECTION TO ORACLE
    (SELECT * FROM Fails   WHERE ROWNUM <= 50  );
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;


 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PW="&path");
    CREATE TABLE Modes_Fields as
    SELECT * FROM CONNECTION TO ORACLE
	(SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH
             FROM ALL_TAB_COLUMNS   WHERE TABLE_NAME='Modes' );
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;

 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PW="&path");
    CREATE TABLE Modes_Rows as
    SELECT * FROM CONNECTION TO ORACLE
    (SELECT * FROM Modes   WHERE ROWNUM <= 50  );
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;



ODS LISTING CLOSE;
ODS TAGSETS.ExcelXP FILE="myDBMS.xml" PATH="&JES.output" ;

ODS TAGSETS.ExcelXP OPTIONS(sheet_name='DB_Tables');
    TITLE "DB_Tables";    PROC PRINT DATA=DB_Tables    NOOBS; RUN;
ODS TAGSETS.ExcelXP OPTIONS(sheet_name='Units_Fields');
    TITLE "Units_Fields"; PROC PRINT DATA=Units_Fields NOOBS; RUN;
ODS TAGSETS.ExcelXP OPTIONS(sheet_name='Units_Rows');
    TITLE "Units_Rows";   PROC PRINT DATA=Units_Rows   NOOBS; RUN;

ODS TAGSETS.ExcelXP OPTIONS(sheet_name='Fails_Fields');
    TITLE "Fails_Fields"; PROC PRINT DATA=Fails_Fields NOOBS; RUN;
ODS TAGSETS.ExcelXP OPTIONS(sheet_name='Fails_Rows');
    TITLE "Fails_Rows"; PROC PRINT DATA=Fails_Rows NOOBS; RUN;

ODS TAGSETS.ExcelXP OPTIONS(sheet_name='Modes_Fields');
    TITLE "Modes_Fields"; PROC PRINT DATA=Modes_Fields NOOBS; RUN;
ODS TAGSETS.ExcelXP OPTIONS(sheet_name='Modes_Rows');
    TITLE "Modes_Rows"; PROC PRINT DATA=Modes_Rows NOOBS; RUN;

ODS TAGSETS.ExcelXP CLOSE;
ODS LISTING;
