

 %LET user=my_user; %LET pw =my_password; %LET path=my_path;
 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PATH="&path");
    CREATE TABLE DB_Tables AS
    SELECT * FROM CONNECTION TO ORACLE
      (SELECT OWNER, TABLE_NAME, NUM_ROWS, AVG_ROW_LEN  FROM ALL_TABLES);
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;


 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PATH="&path");
    CREATE TABLE DB_Views AS
    SELECT * FROM CONNECTION TO ORACLE
      (SELECT OWNER, VIEW_NAME FROM ALL_VIEWS);
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;


 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PATH="&path");
    CREATE TABLE Units_Fields AS
    SELECT * FROM CONNECTION TO ORACLE
    (SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH 
             FROM ALL_TAB_COLUMNS   WHERE TABLE_NAME='UNITS' );
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;

 PROC SQL;
    CONNECT TO ORACLE(USER=&user PW=&pw PATH="&path");
    CREATE TABLE Units_Rows AS
    SELECT * FROM CONNECTION TO ORACLE
    (SELECT * FROM Units   WHERE ROWNUM <= 3  );
    %PUT &SQLXMSG;
    DISCONNECT FROM ORACLE;
 QUIT;



