* S11_3_4b.sas
*
* Adding a computed variable;
* Demonstrate timing of the various compute blocks
* compare the PERCENT column in the output data set 
* with that generated by s11_3_4a; 

title1 'Summary Lines with a Percentage';
proc report data=sashelp.class(where=(age in(12,13))) 
            out=out11_3_4b nowd;
   column age sex n percent;
   define age    / group;
   define sex    / group 'Gender' format=$6.;
   define n      / 'N' format=2.;
   define percent/ computed format=percent8. 'Percent';

   break after age / summarize suppress skip;
   rbreak afterbbb / summarize;

   compute before;
      totn = n;
   endcomp;
   compute before age;
      totage = n;
   endcomp;

   * This will be the LAST block to 
   * execute on the AFTER AGE summary rows;
   * NOTICE in the report how this number replaces the 
   * PERCENT calculated by the percent compute block.;
   compute after age;
      percent=.666;
   endcomp;

   * This calculation of percent is executed
   * first for EACH report row.  Since it does
   * NOT depend on any temporary values it is a 
   * constant;
   compute percent;
      percent=.555; 
   endcomp;
   run;

proc print data=out11_3_4b;
run;
