
DATA new; 
	DO i = 1 TO 2500;
		X=RANPOI(0, 100);
		OUTPUT New;
	END;
RUN;

GOPTIONS RESET=ALL GUNIT=PCT HTEXT=3 FTEXT=SWISSB;
PROC UNIVARIATE DATA=New;
	VAR X;
	HISTOGRAM X / Normal(MU=EST SIGMA=EST);
	INSET N MEAN STD NORMAL(AD ADPVAL) / HEIGHT=2.5 FORMAT=5.2 POSITION=NE;
RUN; QUIT;

%MACRO simpleMacro(dataSetName);
  TITLE "Distribution of 100 Random Poisson Variables";
  PROC UNIVARIATE DATA=&dataSetName;
	VAR X;
	HISTOGRAM X / Normal(MU=EST SIGMA=EST);
	INSET N MEAN STD NORMAL(AD ADPVAL) / 
	HEIGHT=2.5 FORMAT=5.2 POSITION=NE;
  RUN; QUIT;
%MEND simpleMacro;
%simpleMacro(New)
 
ODS HTML PATH="&jes.web" (URL=NONE) BODY = "test.html";
	%simpleMacro(New)
ODS HTML CLOSE;

PROC SETINIT NOALIAS; RUN;
