
PROC DATASETS LIBRARY=WORK MEMTYPE=DATA GENNUM=ALL KILL; QUIT;
PROC DATASETS LIBRARY=JES MEMTYPE=DATA GENNUM=ALL KILL; QUIT;
%LET Path=&JES.sample_code/ch_0/;
%INCLUDE "&Path.ch2_data_sets.sas";
%INCLUDE "&Path.ch4_data_sets.sas";
%INCLUDE "&Path.random_test_results.sas";
%INCLUDE "&Path.random_test_results_ex.sas";
%INCLUDE "&Path.get_colors.sas";
%INCLUDE "&Path.quality_data.sas";
%INCLUDE "&Path.quality_data_p.sas";
%INCLUDE "&Path.quality_data_ex.sas";
%INCLUDE "&Path.random_lifetimes.sas";
%INCLUDE "&Path.rates_by_year.sas";

%MACRO Print_Data_Sets;
%let path=c:\AAAA\SAS_Book\ch_0;
OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\ch2.doc" new; RUN;
TITLE "JES.Contacts"; PROC PRINT DATA=JES.Contacts NOOBS HEADING=HORIZONTAL; RUN;
TITLE "JES.TimeStamp"; PROC PRINT DATA=JES.TimeStamp NOOBS HEADING=HORIZONTAL; RUN;
TITLE "JES.Poisson"; PROC PRINT DATA=JES.Poisson NOOBS; RUN;
TITLE "JES.Units"; PROC PRINT DATA=JES.Units NOOBS; RUN;
TITLE "JES.Fails"; PROC PRINT DATA=JES.FaiLs NOOBS; RUN;
TITLE "JES.Rates"; PROC PRINT DATA =JES.Rates NOOBS; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;

%let path=c:\AAAA\SAS_Book\ch_0;
OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\ch4.doc" new; RUN;
TITLE "JES.Units_U"; PROC PRINT DATA=JES.Units_U NOOBS; RUN;
TITLE "JES.Modes"; PROC PRINT DATA=JES.Modes NOOBS; RUN;
TITLE "JES.Fails_Codes"; PROC PRINT DATA=JES.Fails_Codes NOOBS; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;

%let path=c:\AAAA\SAS_Book\ch_0;
OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\results.doc" new; RUN;
TITLE "JES.Results"; PROC PRINT DATA=JES.Results NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;

OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\results_1.doc" new; RUN;
TITLE "JES.Results_1"; PROC PRINT DATA=JES.Results_1 NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;

OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\results_tab_1.doc" new; RUN;
TITLE "JES.Results_Tab_1"; PROC PRINT DATA=JES.Results_Tab_1 NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;

OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\results_tab_2.doc" new; RUN;
TITLE "JES.Results_Tab_2"; PROC PRINT DATA=JES.Results_Tab_2 NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;


OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\wafer_map.doc" new; RUN;
TITLE "JES.Wafer_Map"; PROC PRINT DATA=JES.Wafer_Map NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;

OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\wafer_data.doc" new; RUN;
TITLE "JES.Wafer_Data"; PROC PRINT DATA=JES.Wafer_Data NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;

OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\first.doc" new; RUN;
TITLE "JES.First"; PROC PRINT DATA=JES.First NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;
OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\first_sum.doc" new; RUN;
TITLE "JES.First_Sum"; PROC PRINT DATA=JES.First_Sum NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\prod.doc" new; RUN;
TITLE "JES.Production_2"; PROC PRINT DATA=JES.Production_2 NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;

%let path=c:\AAAA\SAS_Book\ch_0;
OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\lifetest.doc" new; RUN;
TITLE "JES.LifeTest"; PROC PRINT DATA=JES.LifeTest NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
ODS CSVALL 	file="&path.\lifetest.csv";
PROC PRINT DATA=JES.LifeTest NOOBS; RUN;
ODS CSVALL CLOSE;
OPTIONS CENTER DATE NUMBER;

OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\repair.doc" new; RUN;
TITLE "JES.Repair"; PROC PRINT DATA=JES.Repair NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;

OPTIONS NOCENTER NODATE LINESIZE=80 NONUMBER;
PROC PRINTTO file="&path.\rates.doc" new; RUN;
TITLE "JES.Vendor_List"; PROC PRINT DATA=JES.Vendor_List NOOBS HEADING=HORIZONTAL; RUN;
TITLE "JES.Rates_2006"; PROC PRINT DATA=JES.Rates_2006 NOOBS HEADING=HORIZONTAL; RUN;
TITLE "JES.Rates_2007"; PROC PRINT DATA=JES.Rates_2007 NOOBS HEADING=HORIZONTAL; RUN;
TITLE "JES.Rates_2008"; PROC PRINT DATA=JES.Rates_2008 NOOBS HEADING=HORIZONTAL; RUN;
TITLE;
PROC PRINTTO; RUN;
OPTIONS CENTER DATE NUMBER;

%MEND Print_Data_Sets;
